name: CI - Test HTML

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Vérifier la présence du fichier
        run: |
          test -f index.html
          echo "index.html trouvé ✅"

      - name: Test HTML (validation basique)
        run: |
          echo "Validation basique du HTML..."
          grep -qi "TP DevOps" index.html
          echo "OK : le contenu attendu est présent"
